services:
  php:
    image:          php:8.1.14-fpm
    container_name: php
    restart:        always
    working_dir:    /var/www/html
    volumes:
      - ./php:/var/www/html
    container_name: php
    command: php-fpm

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./php:/var/www/html
    container_name: nginx
    #restart: always
    ports:
      # - 443:443
      - 80:80

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    #restart: always
    ports:
      - "53603:53603"
      - "5055:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@abc.com
      PGADMIN_DEFAULT_PASSWORD: 123456

  postgres:
    image: postgres
    container_name: postgres
    #restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myProjectDB
      POSTGRES_USER: myName
      POSTGRES_PASSWORD: myPassword
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
      #POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - 5432:5432      
